import { ApiProperty } from '@nestjs/swagger';

export class PaymentChargeCardResponseDto {
    @ApiProperty({
        description:
            'Payment outcome. "3ds_required" means render threeDsHtml then call /3ds-complete. "success" means the card was charged directly (no 3DS needed). "failed" means the card was declined.',
        enum: ['3ds_required', 'success', 'failed'],
        example: 'success',
    })
    status: string;

    @ApiProperty({
        description: 'Unique transaction reference generated by VestraPay',
        example: 'VPY_MMARA6NS_B19910D6DA76',
    })
    reference: string;

    @ApiProperty({
        description:
            'HTML snippet containing the 3DS iframe challenge. Only present when status is "3ds_required". Inject this directly into the DOM — it auto-submits the 3DS flow. Listen for the iframe to redirect to your page, then call POST /charge/card/3ds-complete with the reference.',
        required: false,
        nullable: true,
        example: null,
    })
    threeDsHtml?: string;
}
