[build]
dockerfilePath = "services/api/ci/dockerfile"
dockerContext = "."
watchPatterns = ["services/api/**", "pnpm-lock.yaml"]

[deploy]
healthcheckPath = "/api/public/health/liveness"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
