export const CARD_PROCESSOR = 'CARD_PROCESSOR';
export const BANK_TRANSFER_PROCESSOR = 'BANK_TRANSFER_PROCESSOR';
export const BANK_PAYMENT_PROCESSOR = 'BANK_PAYMENT_PROCESSOR';
export const USSD_PROCESSOR = 'USSD_PROCESSOR';

export const ALATPAY_BANK_TRANSFER_PROCESSOR =
    'ALATPAY_BANK_TRANSFER_PROCESSOR';
export const KORAPAY_BANK_TRANSFER_PROCESSOR =
    'KORAPAY_BANK_TRANSFER_PROCESSOR';
export const KORAPAY_BANK_PAYMENT_PROCESSOR = 'KORAPAY_BANK_PAYMENT_PROCESSOR';

export const MPGS_CARD_PROCESSOR = 'MPGS_CARD_PROCESSOR';
export const KORAPAY_CARD_PROCESSOR = 'KORAPAY_CARD_PROCESSOR';
