FROM node:lts-alpine
LABEL maintainer="dev@vestrapay.io"

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate
COPY package.json ./

RUN pnpm install

RUN touch .env

COPY . .

RUN pnpm db:generate

EXPOSE 3000

CMD [ "pnpm", "start:dev" ]
